### ISSUE TITLE
Is there a tutorial to update this addon?

### ISSUE THREAD

**Issue by albcunha** [divio/aldryn-wagtail#3]
Hello Guys! Is there a tutorial that teaches how to update? I saw past changelos and it seems the only necesssary change is the package version. It would be greate to update it to the new wagtail 1.12 👍

**Comment by jmelett** [comment]
@albcunha so far that has been the case! I've checked quickly the last release notes of wagtail (e.g. [1.10](http://docs.wagtail.io/en/latest/releases/1.10.html)) and couldn't find anything, which needs to be addressed in the [aldryn_config.py](https://github.com/aldryn/aldryn-wagtail/blob/master/aldryn_config.py)

As for the tutorial, I'll check with @evildmp if we can write down some instructions to help with that.

**Comment by evildmp** [comment]
Hello @albcunha - yes, you will find the how-guide at http://divio-cloud-developer-handbook.readthedocs.io/en/latest/how-to/update-existing-addon.html.
